<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="pytest" skips="0" tests="3" time="0.110"><testcase classname="test_submit.TestChallenge4" file="test_submit.py" line="6" name="test_verify_signature" time="0.002110004425048828"><system-out>{&apos;language&apos;: &apos;Python&apos;}
</system-out></testcase><testcase classname="test_submit.TestChallenge4" file="test_submit.py" line="9" name="test_verify_signature_fail" time="0.0005548000335693359"><system-out>{&apos;error&apos;: 2}
</system-out></testcase><testcase classname="test_submit.TestChallenge4" file="test_submit.py" line="12" name="test_create_token" time="0.0"></testcase></testsuite>